### ISSUE TITLE
Remover o index.php do $indexPage (.env)

### ISSUE THREAD

**Issue by devajmeireles** [onovaes/docker-ci4#2]
O uso de 'index.php' no $indexPage faz com que 'index.php' não saia da URL. O ideal seria remove-lo para que fique desta forma: https://localhost:8080/ (ao invés de: https://localhost:8080/index.php/ quando usar algumas funções do CI4)

Solução: .env

app.indexPage = ''

**Comment by onovaes** [comment]
Perfeito @ajmeireles , pode abrir um PR

**Comment by onovaes** [comment]
Merge feito
